### ISSUE TITLE
Python error on load.

### ISSUE THREAD

**Issue by giulioungaretti** [neilagabriel/vim-geeknote#24]
```python
"/var/folders/wv/96m371n13y31crwjfsmqr6f40000gn/T/__GeeknoteExplorer__YFPKph" 0L, 0C
Error detected while processing function Vim_GeeknoteToggle:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/giulio/.vim/bundle/vim-geeknote/plugin/vim_geeknote.py", line 177, in GeeknoteToggle
    explorer.show()
  File "/Users/giulio/.vim/bundle/vim-geeknote/plugin/explorer.py", line 774, in show
    self.initView()
  File "/Users/giulio/.vim/bundle/vim-geeknote/plugin/explorer.py", line 560, in initView
    setWindowVariable(wnum, 'winfixwidth', True)
  File "/Users/giulio/.vim/bundle/vim-geeknote/plugin/utils.py", line 95, in setWindowVariable
    vim.windows[wnum-1].options[var] = value
AttributeError: options
```

geeknote login is fine,  I can't figure out where the options attribute comes from :D

**Comment by neilagabriel** [comment]
What platform are you running?

**Comment by adammulligan** [comment]
Hi,

Thanks for creating this, I'm excited about using markdown properly with Evernote! However, I have the same issue as @giulioungaretti:

```
Error detected while processing function Vim_GeeknoteToggle:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/adammulligan/.vim/bundle/vim-geeknote/plugin/vim_geeknote.py", line 177, in GeeknoteToggle
    explorer.show()
  File "/Users/adammulligan/.vim/bundle/vim-geeknote/plugin/explorer.py", line 774, in show
    self.initView()
  File "/Users/adammulligan/.vim/bundle/vim-geeknote/plugin/explorer.py", line 560, in initView
    setWindowVariable(wnum, 'winfixwidth', True)
  File "/Users/adammulligan/.vim/bundle/vim-geeknote/plugin/utils.py", line 95, in setWindowVariable
    vim.windows[wnum-1].options[var] = value
AttributeError: options
```

I've got it working on a Ubuntu box, however here I'm running on OS X Yosemite 10.10.2, with python 2.7.9. Here's my vim build:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

Let me know if you need anymore info!

**Comment by adammulligan** [comment]
I've actually just fixed this, sorry for jumping the gun a little on posting an issue and cluttering up your inbox.

My fix was pretty simple: I uninstalled and reinstalled vim using Homebrew (now on 7.4.488), deleted my `~/.vim/bundle` directory contents, and re-ran `:BundleInstall`, and now Geeknote works fine.

**Comment by giulioungaretti** [comment]
sorry for late answer but yeah, same fix as @adammulligan .
Old version of vim on OS X. I think it's a vim-python version mismatch issue. 

Thank you again for the tool :D

**Comment by neilagabriel** [comment]
Sorry for not being of any help on the OSX side. Hopefully I'll have a system to test on soon. Glad you got it working though.

**Comment by kaldrenon** [comment]
I'm getting this now, in vim and in neovim on OSX Yosemite, Python 2.7.10

Uninstalling and reinstalling vim has not done anything to help.

**Comment by neilagabriel** [comment]
@kaldrenon, unfortunately, I still don't have an OSX system to try this on. All I can say is that based on 100% of other OSX-related issues that have come up so far, something is most likely broken in your vim installation related to python.

**Comment by kaldrenon** [comment]
Interestingly, it works in MacVim, so I can still use Geeknote while I figure out what's going on. But that also supports the idea that it's probably not `vim-geeknote`'s fault because one of the clients works.

Thanks for the quick reply; I'll be sure to update here if I ever get it worked out.

**Comment by neilagabriel** [comment]
@kaldrenon, I just noticed that you said you were using neovim. As far I know, you'll be the first to try the plugin with Neovim on OSX. I just recently added support for Neovim. Are you getting the same error as @giulioungaretti when you use neovim?

**Comment by kaldrenon** [comment]
Yessir - same error in both `vim` (7.3) and `neovim` ([7be75a02917b40e5791e3f98d177f833a348df35](https://github.com/neovim/neovim/commit/7be75a02917b40e5791e3f98d177f833a348df35)).

**Comment by kaldrenon** [comment]
Upgrading to `vim` (version 7.4.769) resulted in the error going away.

In `neovim` I now get the following:

    Error detected while processing function Vim_GeeknoteToggle..provider#python#Call:
    line   18:
    IndexError('list index out of range',)
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
        rv = self._request_cb(name, args)
      File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
        walk(self._in, args, self, name, 'request'))
      File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
        rv = handler(*args)
      File "/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
        exec(script, self.module.__dict__)
      File "<string>", line 2, in <module>
    IndexError: list index out of range

I can open a separate issue for this if desired.

**Comment by neilagabriel** [comment]
This looks very much like an issue I addressed in my last set of changes to
support neovim. Can you confirm that you are using the latest vim-geeknote
code?

**Comment by kaldrenon** [comment]
Confirmed - I am on https://github.com/neilagabriel/vim-geeknote/commit/12304efb0ac9ed1c63d8de3d348663310870fee6

**Comment by neilagabriel** [comment]
Looks like I screwed up my last commit and forgot a file. Please try again with 039b72bb5c1b0dabe17b716ac88d546ad8f6143

**Comment by kaldrenon** [comment]
Fixed my problem. Thank you! :clap:
