### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by ashiklom** [neilagabriel/vim-geeknote#29]
I've had no issues using this plugin with Vim. However, when I launch it in [Neovim](https://github.com/neovim/neovim), I get the following error on trying the `:Geeknote` command....

```
Error detected while processing function Vim_GeeknoteToggle..provider#python#Call:
line   12:
IndexError('list index out of range',)
```

...and this error on the `:GeeknoteSync` command.

```
Error detected while processing function Vim_GeeknoteSync..provider#python#Call:
line   12:
IndexError('list index out of range',)
```

I'm guessing this is because of some difference in the underlying plugin APIs. Do you have any plans for porting this plugin to Neovim? An example of a plugin ported from Vim to Neovim is the vim R plugin ([original](https://github.com/vim-scripts/Vim-R-plugin), [port](https://github.com/jalvesaq/Nvim-R)).

**Comment by neilagabriel** [comment]
Not currently no. I've heard of neovim but I've never had reason to use it. Should I check it out?

**Comment by ashiklom** [comment]
I would at least look into it. I've never delved into Vim plugins enough to really understand the differences in the plugin API, but they claim it's more stable and easier to use with external software (like Python and Ruby). There are features of it I recognize and appreciate, though, like the fact that all Vim language plugins (`--enable-python` and such) are enabled by default, the built in terminal emulator (which is much nicer than Vim), and most of all, just how actively it's being developed and updated. I originally switched for the latter reason, because applying Vim patches to get newer features was a pain. Also, I don't follow exactly what they're doing very closely, but the general idea of cleaning and optimizing Vim's ancient C code seems pretty smart to me. 

But all that's just my opinion. As an actual Vim plugin developer, you'd know a lot better than me :smiley:

**Comment by scottbaron** [comment]
RE: VIM Geeknote - to you and the geeknote team, wonderful job. I wish you continued success with the project. Question - as instructed when exiting a file and you want to write :w because as you know if you :x the orientation of the screen reverses the position of the explorer vs the file editing screen. Finally, when that happens there is a long series of number along side the notes and notebooks. What are they? Example below: Untitled n[fc9608be-b8ba-4f03-8cf0-7be88e7852ba(0)]↲

**Comment by kaldrenon** [comment]
I'll add my +1 in hopes of using Geeknote in Neovim. Similarly unsure of what the task would take, but I'd love to see it.

**Comment by smarquez1** [comment]
+1. Neovim + Geeknote sounds like an amazing combination

**Comment by yankcrime** [comment]
Another :+1: For NeoVim support.

**Comment by neilagabriel** [comment]
I just built and installed NeoVim and after symlinking my .vim to .nvim and .vimrc to .nvimrc everything just worked.@ashiklom, are you still seeing the error above? Has anyone tried?

NVIM 0.0.0-alpha+201508051908 (compiled Aug  6 2015 01:18:39)
Commit: 5a195858657e1c494e77ea868073d2f3664cdb60

**Comment by neilagabriel** [comment]
@scottbaron, the series of letters and numbers that appear to the right of your notebooks and notes are GUIDs (plus some other characters) that uniquely identify the notebook, note, or tag. I need that information to handle changes that you make. You should not need to worry about this information, just please do not delete it as that may cause unpredictable behavior.

**Comment by neilagabriel** [comment]
I take it back, though it did work once I tried launching vim-geeknote in neovim again and this time I see the errors. Let me look into it.

**Comment by neilagabriel** [comment]
Neovim support added in ee918cfc22fd8b20b75c077d05c4df2fb5903c5b.

Unfortunately I had to add a new neovim-specific step to the installation process. See the README.md for details. If I manage to figure out how to detect at runtime when the plugin is being used from Neovim, I will remove this extra step. Please let me know how it works out for you. File new bugs for any new issues that pop up (if any).

**Comment by neilagabriel** [comment]
Disregard my comments above on the extra installation step. I managed to figure out how to detect neovim at runtime. Just pull down the latest code and everything should just work.
